# Zadanie 4

### Tworzenie data frame

In [16]:
import pandas as pd

df = pd.DataFrame({
    "dzien": [1, 1, 2, 2, 3, 3],
    "produkt": ["A", "B", "A", "B", "A", "C"],
    "produkcja": [120, 95, 130, 100, 125, 80],
    "koszt": [5000, 4200, 5100, 4300, 5050, 3900],
    "zmiana": ["poranna", "nocna", "poranna", "nocna", "poranna", "nocna"]
})

print(df)

   dzien produkt  produkcja  koszt   zmiana
0      1       A        120   5000  poranna
1      1       B         95   4200    nocna
2      2       A        130   5100  poranna
3      2       B        100   4300    nocna
4      3       A        125   5050  poranna
5      3       C         80   3900    nocna


### Sprawdzanie typu danych i kształtu array

In [17]:
import numpy as np

produkcja = np.array([120, 95, 130, 100, 125, 80])

print(produkcja)
print("shape:", produkcja.shape)
print("dtype:", produkcja.dtype)

[120  95 130 100 125  80]
shape: (6,)
dtype: int64


### Operacje wektorowe

In [18]:
plan = np.array([110, 100, 120, 100, 120, 90])

print("Produkcja + 10:", produkcja + 10)
print("Produkcja * 2:", produkcja * 2)
print("Różnica:", produkcja - plan)
print("Realizacja [%]:", produkcja / plan * 100)

Produkcja + 10: [130 105 140 110 135  90]
Produkcja * 2: [240 190 260 200 250 160]
Różnica: [ 10  -5  10   0   5 -10]
Realizacja [%]: [109.09090909  95.         108.33333333 100.         104.16666667
  88.88888889]


Które dni są poniżej planu: 2 i 6 <br>
Czy odchylenia są istotne: raczej nie ale wymagane jest zweryfikowanie odchylenia standardowego <br>
Czy proces wymaga korekty <br>

### Statystyki

In [19]:
print("Średnia:", np.mean (produkcja))
print("Min:", np.min(produkcja))
print("Max:", np.max (produkcja))
print("Odchylenie:", np.std(produkcja))

Średnia: 108.33333333333333
Min: 80
Max: 130
Odchylenie: 17.950549357115012


### DataFrame

In [20]:
print(df)

   dzien produkt  produkcja  koszt   zmiana
0      1       A        120   5000  poranna
1      1       B         95   4200    nocna
2      2       A        130   5100  poranna
3      2       B        100   4300    nocna
4      3       A        125   5050  poranna
5      3       C         80   3900    nocna


### Filtrowanie

In [21]:
wysoka = df[df["produkcja"] > 100]
print(wysoka)

   dzien produkt  produkcja  koszt   zmiana
0      1       A        120   5000  poranna
2      2       A        130   5100  poranna
4      3       A        125   5050  poranna


### Grupowanie

In [22]:
print(df.groupby("produkt") ["produkcja"].mean())
print(df.groupby("zmiana") ["koszt"].sum())

produkt
A    125.0
B     97.5
C     80.0
Name: produkcja, dtype: float64
zmiana
nocna      12400
poranna    15150
Name: koszt, dtype: int64


In [23]:
#koszt jednostkowy
sredni_koszt_produktu = df.groupby("produkt")["koszt"].sum()/df.groupby("produkt")["produkcja"].sum()
print(sredni_koszt_produktu)
#efektywność
df["efektywnosc"] = df["produkcja"] / df ["koszt"]
df["koszt_jednostkowy"] = df["koszt"] / df["produkcja"]
print(df[["produkt", "produkcja", "koszt", "koszt_jednostkowy", "zmiana"]])

produkt
A    40.400000
B    43.589744
C    48.750000
dtype: float64
  produkt  produkcja  koszt  koszt_jednostkowy   zmiana
0       A        120   5000          41.666667  poranna
1       B         95   4200          44.210526    nocna
2       A        130   5100          39.230769  poranna
3       B        100   4300          43.000000    nocna
4       A        125   5050          40.400000  poranna
5       C         80   3900          48.750000    nocna


In [24]:
print(df.groupby("zmiana")["efektywnosc"])

### Mini zadanie

Wykonaj:
1. Tablica NumPy: [50, 60, 70, 80]
2. Pomnóż przez 2
3. Oblicz średnią i odchylenie
4. Stwórz DataFrame
5. Filtruj produkcję >100
6. Grupuj po produkcie

In [25]:
import numpy as np
import pandas as pd
tb = np.array([50, 60, 70, 80, 90])
print(tb)
tb = tb*2
srednia = tb.mean()
odchylenie_standardowe = tb.std()
#zbudowanie dataframe
df = pd.DataFrame({
    "produkcja": tb,
    "produkt": ["A", "A", "B", "C", "A"]
})
print(df)
#filtrowanie
df_100 = df[df['produkcja']>100]
print(df_100)
df_produkt = df_100.groupby('produkt')['produkcja'].sum()
print(df_produkt)

[50 60 70 80 90]
   produkcja produkt
0        100       A
1        120       A
2        140       B
3        160       C
4        180       A
   produkcja produkt
1        120       A
2        140       B
3        160       C
4        180       A
produkt
A    300
B    140
C    160
Name: produkcja, dtype: int64


### Przygotowanie danych

In [26]:
import numpy as np

df = pd.DataFrame({
    "produkt": ["A", "a", "B", None, "C", "C"],
    "produkcja": [120, 0, 95, 110, -5, 130],
    "plan": [100, 100, None, 105, 120, 125],
    "koszt": ["5000", "4800", None, "5200", "99999", "5100"]
})

print(df)

  produkt  produkcja   plan  koszt
0       A        120  100.0   5000
1       a          0  100.0   4800
2       B         95    NaN    NaN
3     NaN        110  105.0   5200
4       C         -5  120.0  99999
5       C        130  125.0   5100


In [27]:
print(df.isnull().sum())

produkt      1
produkcja    0
plan         1
koszt        1
dtype: int64


kolumny wymagające poprawy: produkt, plan, koszt

In [28]:
df["produkt"] = df["produkt"].fillna("0")
df["plan"] = df["plan"].fillna(0)
df["koszt"] = df["koszt"].fillna("0")

zero jest sensowne dla kolumn liczbowych nie do końća dla kolumn z wartościami tekstowymi

In [29]:
#usunięcie linii bez nazwy produktu
df = df[df['produkt'] != "0"]
print(df)

  produkt  produkcja   plan  koszt
0       A        120  100.0   5000
1       a          0  100.0   4800
2       B         95    0.0      0
4       C         -5  120.0  99999
5       C        130  125.0   5100


In [30]:
#typ danych
df["koszt"] = df["koszt"].astype(float)

# czyszczenie
df = df[df["produkcja"] > 0]
df = df[df["koszt"] > 0]

In [31]:
#standaryzacja
df["produkt"] = df["produkt"].str.upper()

#wydajność
df["wydajnosc"] = df["produkcja"] / df["plan"] * 100

#statystyki i anomalie
print(df.describe())

        produkcja       plan        koszt   wydajnosc
count    2.000000    2.00000     2.000000    2.000000
mean   125.000000  112.50000  5050.000000  112.000000
std      7.071068   17.67767    70.710678   11.313708
min    120.000000  100.00000  5000.000000  104.000000
25%    122.500000  106.25000  5025.000000  108.000000
50%    125.000000  112.50000  5050.000000  112.000000
75%    127.500000  118.75000  5075.000000  116.000000
max    130.000000  125.00000  5100.000000  120.000000


### Mini zadanie 1 – pełny proces przygotowania i analizy danych

Cel zadania <br>
Student przeprowadza pełny mini-proces analityczny:
<ul>
<li> przygotowanie danych,
<li> czyszczenie,
<li> budowa wskaźników,
<li> identyfikacja problemów,
<li>wyciągnięcie wniosków biznesowych.
</ul>
<br> Treść zadania <br>
Na podstawie podanego datasetu wykonaj kompleksową analizę danych.
Twoim celem jest przygotowanie danych do analizy oraz wyciągnięcie pierwszych wniosków dla
menedżera produkcji.

#### KROK 1 – Wczytanie i wstępna analiza danych

In [32]:
#definicja df
df = pd.DataFrame({
    "produkt": ["A", "a", "B", None, "C", "C"],
    "produkcja": [120, 0, 95, 110, -5, 130],
    "plan": [100, 100, None, 105, 120, 125],
    "koszt": ["5000", "4800", None, "5200", "99999", "5100"]
})

print(df)
print(df.shape)
print(df.dtypes)
print(df.head())

  produkt  produkcja   plan  koszt
0       A        120  100.0   5000
1       a          0  100.0   4800
2       B         95    NaN    NaN
3     NaN        110  105.0   5200
4       C         -5  120.0  99999
5       C        130  125.0   5100
(6, 4)
produkt          str
produkcja      int64
plan         float64
koszt            str
dtype: object
  produkt  produkcja   plan  koszt
0       A        120  100.0   5000
1       a          0  100.0   4800
2       B         95    NaN    NaN
3     NaN        110  105.0   5200
4       C         -5  120.0  99999


#### KROK 2 – Identyfikacja problemów w danych 

znajdź potencjalne błędy:
<ul>
<li>wartości ujemne w produkcji
<li>wartości równe 0
<li>nietypowe wartości (np. bardzo wysokie koszty)
</ul>

In [33]:
df.isnull().sum()


produkt      1
produkcja    0
plan         1
koszt        1
dtype: int64

In [34]:
print(df["produkt"].unique)

<bound method Series.unique of 0      A
1      a
2      B
3    NaN
4      C
5      C
Name: produkt, dtype: str>


#### KROK 3 – Czyszczenie danych

produkt, plan, koszt ma null

In [35]:
df["koszt"] = df["koszt"].astype(float)
df['koszt'] = df['koszt'].replace(0, np.nan)
srednia_koszt = df['koszt'].mean()
df['koszt'] = df['koszt'].fillna(srednia_koszt)
df['plan'] = df['plan'].replace(0, np. nan)
srednia_plan = df['plan'].mean()
df['plan'] = df['plan'].fillna(srednia_plan)
df["produkt"] = df["produkt"].str.upper()
df = df.query('produkcja > 0')
df = df.dropna()
print(df)

  produkt  produkcja   plan    koszt
0       A        120  100.0   5000.0
2       B         95  110.0  24019.8
5       C        130  125.0   5100.0


#### KROK 4 – Tworzenie wskaźników KPI

In [36]:
df["wydajnosc"] = df["produkcja"] / df["plan"] * 100
df["koszt_jednostkowy"] = df["koszt"] / df["produkcja"]
print(df)

  produkt  produkcja   plan    koszt   wydajnosc  koszt_jednostkowy
0       A        120  100.0   5000.0  120.000000          41.666667
2       B         95  110.0  24019.8   86.363636         252.840000
5       C        130  125.0   5100.0  104.000000          39.230769


#### KROK 5 – Analiza danych

In [37]:
# statystyki
df.describe()
print(f"Średnia proukcji: {df.groupby("produkt")["produkcja"].mean()}")
print(f"Suma kosztów: {df.groupby("produkt")["koszt"].sum()}")

Średnia proukcji: produkt
A    120.0
B     95.0
C    130.0
Name: produkcja, dtype: float64
Suma kosztów: produkt
A     5000.0
B    24019.8
C     5100.0
Name: koszt, dtype: float64


#### KROK 6 – Identyfikacja anomalii

In [38]:
df_max = df["koszt"].max()
df_min = df["produkcja"].min()
print(f"Maksimum kosztu: {df_max}")
print(f"Minimum produkcja: {df_min}")
print(df)


Maksimum kosztu: 24019.8
Minimum produkcja: 95
  produkt  produkcja   plan    koszt   wydajnosc  koszt_jednostkowy
0       A        120  100.0   5000.0  120.000000          41.666667
2       B         95  110.0  24019.8   86.363636         252.840000
5       C        130  125.0   5100.0  104.000000          39.230769


In [39]:
df_filtr = df[df["koszt"] > 10000]
df_mediana = df_filtr["koszt"].median()
df_średnia = df_filtr["koszt"].mean()
df_max = df_filtr["koszt"].max()
df_min = df_filtr["koszt"].min()
print(f"Mediana: {df_mediana}")
print(f"Średnia: {df_średnia}")
print(f"Max: {df_max}")
print(f"Min: {df_min}")

Mediana: 24019.8
Średnia: 24019.8
Max: 24019.8
Min: 24019.8


Najbardziej wydajny produkt: A <br>
Nieproporcjonalnie wysokie koszty: B <br>
Podejrzane wartości: ujemna produkcja, koszt 9999 <br>
Są to błędy <br>
Produkcja produktu B: najmniej wydajna i największe koszty <br>
Przy małej próbie danych uzupełniamy, przy dużej próbie można usunąć <br>
Sprawdzenie procesu zapisu danych i ich jakość oraz zmodyfikować proces produkcji B lub z niego zrezygnować <br>

### Mini zadanie 2 (samodzielne – rozszerzone)

In [40]:
# utworzenie tablicy
tb = np.array([50, 60, 70, 80])
print(f"liczba elementów: {tb.shape}")
print(f"typ danych: {tb.dtype}")

liczba elementów: (4,)
typ danych: int64


In [41]:
#operacja na danych
tb2 = tb*2
tb2_10 = tb2+10
tb = tb2_10-5
print(tb)

[105 125 145 165]


In [42]:
#statystyki
srednia = tb.mean()
minimum = tb.min()
maksimum = tb.max()
odchylenie_standardowe = tb.std()
print(f"średnia: {srednia}")
print(f"minimum: {minimum}")
print(f"maksimum: {maksimum}")
print(f"odchylenie standardowe: {round(odchylenie_standardowe,1)}")
print(f"stosunek odchylenia do średniej: {round(odchylenie_standardowe/srednia,1)}")

średnia: 135.0
minimum: 105
maksimum: 165
odchylenie standardowe: 22.4
stosunek odchylenia do średniej: 0.2


In [15]:
print(tb)

[100 120 140 160 180]


Odchylenie standardowe jest duże w stosunku do średniej, więc można przypuszczać że dane nie są stabilne. <br>
wartości w przedziale 100-180

## Część 2: biblioteka pandas

In [47]:
#utworzenie danych tabelarycznych
df = pd.DataFrame({
    "produkt": ["A", "B", "A", "B", "C"],
    "produkcja": [100, 120, 90, 130, 80],
    "koszt": [5000, 6000, 4500, 6500, 4000]
})

#wyświetlenie danych
print("Wyświetlenie danych")
print(df)
#sprawdzenie typów danych
print("Typy danych")
print(df.dtypes)
#pierwszy wiersz danych
print("Pierwszy wiersz danych")
print(df.head(1))
#wyświetlenie kształtu tabeli
print("Kształt tabeli")
print(df.shape)

Wyświetlenie danych
  produkt  produkcja  koszt
0       A        100   5000
1       B        120   6000
2       A         90   4500
3       B        130   6500
4       C         80   4000
Typy danych
produkt        str
produkcja    int64
koszt        int64
dtype: object
Pierwszy wiersz danych
  produkt  produkcja  koszt
0       A        100   5000
Kształt tabeli
(5, 3)


Tabela zawiera **5 wierszy** i **3 kolumny**. <br>
Jedna kolumna **string** (produkt) i dwie typu **integer** (produkcja i koszt)

In [48]:
#tworzenie nowej kolumny w tabeli
df['sprzedaż'] = df['produkcja']*df['koszt']
print(df)

  produkt  produkcja  koszt  sprzedaż
0       A        100   5000    500000
1       B        120   6000    720000
2       A         90   4500    405000
3       B        130   6500    845000
4       C         80   4000    320000


In [49]:
#filtrowanie danych
df = df[df['produkcja'] > 100]
print(df)

  produkt  produkcja  koszt  sprzedaż
1       B        120   6000    720000
3       B        130   6500    845000


In [50]:
#sortowanie danych
df=df.sort_values(['produkcja','koszt'], ascending=[False, True])
print(df)

  produkt  produkcja  koszt  sprzedaż
3       B        130   6500    845000
1       B        120   6000    720000


In [52]:
#grupowanie danych
srednia_produkcja = df.groupby("produkt")["produkcja"].mean()
srednia_koszt = df.groupby("produkt")["koszt"].mean()
#wyświetlenie wyników
print(f"Dane o średniej produkcji {srednia_produkcja}")
print(f"Dane o średniej koszt {srednia_koszt}")

Dane o średniej produkcji produkt
B    125.0
Name: produkcja, dtype: float64
Dane o średniej koszt produkt
B    6250.0
Name: koszt, dtype: float64


In [53]:
#dodanie koszt jednostkowy
df['koszt jednostkowy'] = df['koszt']/df['produkcja']
print(df)

  produkt  produkcja  koszt  sprzedaż  koszt jednostkowy
3       B        130   6500    845000               50.0
1       B        120   6000    720000               50.0


### Część 4
#### Zadanie rozszerzające

In [ ]:
#dodanie nowego produktu "D"
produkcja_D = 23000
koszt_D = 2000
nowy_wiersz = {
    "produkt": "D",
    "produkcja": produkcja_D,
    "koszt": koszt_D,
    "sprzedaż": 100,
    "koszt jednostkowy": koszt_D/produkcja_D
}

df = pd.concat([df, pd.DataFrame([nowy_wiersz])], ignore_index=True)
print(df)

  produkt  produkcja  koszt  sprzedaż  koszt jednostkowy
0       B        130   6500    845000          50.000000
1       B        120   6000    720000          50.000000
2       D      23000   2000       100           0.086957
3       D      23000   2000       100           0.086957
4       D      23000   2000       100           0.086957


In [62]:
#zwiększenie kosztu produktu B o 20%
df.loc[df["produkt"] == "B", "koszt"] *= 1.2
print(df)

  produkt  produkcja  koszt  sprzedaż  koszt jednostkowy
0       B        130   7800    845000          50.000000
1       B        120   7200    720000          50.000000
2       D      23000   2000       100           0.086957
3       D      23000   2000       100           0.086957
4       D      23000   2000       100           0.086957


In [65]:
#rekordy o nawyższym koszcie jednostkowym
idx = df['koszt jednostkowy'].idxmax()
df.loc[idx]

produkt                   B
produkcja               130
koszt                  7800
sprzedaż             845000
koszt jednostkowy      50.0
Name: 0, dtype: object

In [66]:
#suma produkcji
suma = df['produkcja'].sum()
print(f"Suma produkcji: {suma}")

Suma produkcji: 69250


In [67]:
#suma kosztów
suma = df['koszt'].sum()
print(f"Suma kosztów: {suma}")

Suma kosztów: 21000
