# Ćwiczenia 3
**Temat: biblioteki NumPy i Pandas**

In [ ]:
#pobranie bibliotek
#pip!install numpy
import numpy as np
print("NumPy został poprawnie zaimportowany")

NumPy został poprawnie zaimportowany


### Tworzenie tablic NumPy
*tablice numpy zoptymalizowane są do obliczeń matematycznych i działania na liczbach*

In [ ]:
#tworzenie tablicy
tablica = np.array([10, 20, 30, 40, 50, 60])
lista = [10,20,30,40, 50]
print(tablica)
print(lista)

[10 20 30 40 50 60]
[10, 20, 30, 40, 50]


In [66]:
print(tablica*2)
print(lista*2)

[ 20  40  60  80 100 120]
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]


#### Właściwość shape
*sprawdzenie wielkości i kształtu tablicy*

In [ ]:
#sprawdzenie rozmiaru i wymiarów tablicy
print(tablica.shape)
#print(lista.shape) atrybut shape działa tylko na tablicy nie na liście
#interpretacja wyników
#(6,) 6 elementów w 1 wymiarze

(6,)


In [ ]:
#tablica wielowymiarowa
macierz = np.array([
    [1,2],
    [2,3]
])
print(macierz.shape)
#interpretacja wyników
#(2,2) po 2 elementy w 2 wymiarach

(2, 2)


In [ ]:
#zadanie praktyczne tworzenie tablic jedno- i wielowymiarowych
macierz_6 = np.array([
    [1,2],
    [3,4],
    [5,6]
])
tablica_6 = np.array([1,2,3,4,5,6])
print(macierz_6.shape)
print(tablica_6.shape)

(3, 2)
(6,)


#### Właściwość dtype
*sprawdzenie rodzajów danych w tablicah*

In [70]:
print(macierz_6.dtype)
print(tablica_6.dtype)

int64
int64


In [71]:
tablica_mix = np.array([1,"2",3,4,5,6])
tablica_ujemne = np.array([-1,-2,-3,-4,-5,6])
tablica_przecinki = np.array([1.1,1.2,1.3])
print(tablica_mix.dtype)
print(tablica_ujemne.dtype)
print(tablica_przecinki.dtype)

<U21
int64
float64


#### Operacje matematyczne na tablicach NumPy
*wykonywane działania matematyczne na wszystkich elementach jednocześnie*

In [72]:
dane1 = tablica_ujemne * 2
dane2 = tablica_ujemne - 2
dane3 = tablica_ujemne + 2
dane4 = tablica_ujemne / 2
print(dane1)
print(dane2)
print(dane3)
print(dane4)

[ -2  -4  -6  -8 -10  12]
[-3 -4 -5 -6 -7  4]
[ 1  0 -1 -2 -3  8]
[-0.5 -1.  -1.5 -2.  -2.5  3. ]


#### Operacje wektorowe na dwóch tablicach

In [73]:
a = np.array([1,2,3])
b = np.array([6,2,9])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 7  4 12]
[-5  0 -6]
[ 6  4 27]
[0.16666667 1.         0.33333333]


In [ ]:
#ćwiczenie: porównanie planu i wykonania

plan = np.array([100, 100, 100, 100, 100])
wykonanie = np.array([95, 102, 98, 105, 99])

roznica = wykonanie - plan
print (roznica)

#porównanie dni
dni_powyzej = dni_powyzej = np.where(roznica > 0)[0] + 1
dni_ponizej = np.where(roznica < 0)[0] + 1
#dopisanie [0] aby wyciągnąć indeksy

print(dni_ponizej)
print(dni_powyzej)

[-5  2 -2  5 -1]
[1 3 5]
[2 4]


In [ ]:
#obliczanie średniej z użyciem np.mean()
tablica_ujemne = np.array([-1,-2,-3,-4,-5,6])
dane1 = tablica_ujemne * 2
print(np.mean(dane1))

-3.0


In [ ]:
print(np.min(dane1))
print(np.max(dane1))
print(np.median(dane1))
#odchylenie standardowe
print(np.std(dane1))
#niskie odchylenie większa stabilność
#duże odchylenie mniejsza stabliność
print(np.mean(dane1))

-10
12
-5.0
7.187952884282608
-3.0


In [ ]:
#zadanie
import numpy as np

dane = np.array([95, 100, 102, 98, 105])

print("Średnia:", np.mean(dane))
print("Minimum:", np.min(dane))
print("Maksimum:", np.max(dane))
print("Odchylenie standardowe:", np.std(dane))

print("Przeciętna wydajność:", np.mean(dane))
print("Najsłabszy wynik:", np.min(dane))
print("Najlepszy wynik:", np.max(dane))
print("Odchylenie standardowe:", np.std(dane))
print("Wyniki są stabilne małe odchylenie standardowe w stosunku do średniej, wariancja na poziomie: ", round((np.std(dane)/np.mean(dane))*100,1),"%")


Średnia: 100.0
Minimum: 95
Maksimum: 105
Odchylenie standardowe: 3.40587727318528
Przeciętna wydajność: 100.0
Najsłabszy wynik: 95
Najlepszy wynik: 105
Odchylenie standardowe: 3.40587727318528
Wyniki są stabilne małe odchylenie standardowe w stosunku do średniej, wariancja na poziomie:  3.4 %


In [ ]:
#mini zadanie 1
dane = np.array([900, 345, 1243, 548, 13, 134, 252265, -200, 3452, -24, -2344, -244])
print("Tablica:", dane)
print("Shape:", dane.shape)
print("Rtype:", dane.dtype)
print("Pomnożone przez 2:", dane * 2)
print("Średnia:", np.mean(dane))
print("Minimum:", np.min(dane))
print("Maksimum:", np.max(dane))
print("Odchylenie standardowe:", np.std(dane))

Tablica: [   900    345   1243    548     13    134 252265   -200   3452    -24
  -2344   -244]
Shape: (12,)
Rtype: int64
Pomnożone przez 2: [  1800    690   2486   1096     26    268 504530   -400   6904    -48
  -4688   -488]
Średnia: 21340.666666666668
Minimum: -2344
Maksimum: 252265
Odchylenie standardowe: 69637.66032989782


#### Biblioteka Pandas

In [ ]:
#import biblioteki
#!pip install pandas
import pandas as pd

#### Tworzenie serii danych

In [ ]:
s = pd.Series([10,20,30])
print(s)
#seria w przeciwieńswtie do tablicy numpy nie jest wierszem a kolumną

0    10
1    20
2    30
dtype: int64


In [ ]:
s = pd.Series(dane1)
print(s)
#można dokonać transpozycji danych np.arrey za pomocą pd.Sereis

0    -2
1    -4
2    -6
3    -8
4   -10
5    12
dtype: int64


#### Tworzenie dataframe

In [82]:
df = pd.DataFrame([
    dane1,
    dane2,
    dane3,
    dane4
])

print(df)

     0    1    2    3     4     5
0 -2.0 -4.0 -6.0 -8.0 -10.0  12.0
1 -3.0 -4.0 -5.0 -6.0  -7.0   4.0
2  1.0  0.0 -1.0 -2.0  -3.0   8.0
3 -0.5 -1.0 -1.5 -2.0  -2.5   3.0


In [83]:
df2 = pd.DataFrame({
    'produkcja': [100, 200, 300],
    'koszt': [500, 300, 203]
})
print(df2)

   produkcja  koszt
0        100    500
1        200    300
2        300    203


#### Sprawdzanie informacji o dancyh
**Użycie funkcji: df.info()**

In [84]:
df2.head(3)

,produkcja,koszt
0,100,500
1,200,300
2,300,203


In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4 non-null      float64
 1   1       4 non-null      float64
 2   2       4 non-null      float64
 3   3       4 non-null      float64
 4   4       4 non-null      float64
 5   5       4 non-null      float64
dtypes: float64(6)
memory usage: 324.0 bytes


#### Grupowanie danych

In [ ]:
import pandas as pd
df = pd.DataFrame({
'produkt': ['A', 'A', 'B', 'B', 'C'],
'produkcja': [100, 120, 90, 95, 110],
'koszt': [5000, 5500, 4500, 4700, 5300]
})

print(df)

df.groupby('produkt') ['produkcja'].sum()
#df.groupby('produkt') ['produkcja'].mean()

  produkt  produkcja  koszt
0       A        100   5000
1       A        120   5500
2       B         90   4500
3       B         95   4700
4       C        110   5300


produkt
A    220
B    185
C    110
Name: produkcja, dtype: int64

### Zadania domowe

#### Filtrowanie danych

In [87]:
df[df['produkcja']>100]
print(df)

  produkt  produkcja  koszt
0       A        100   5000
1       A        120   5500
2       B         90   4500
3       B         95   4700
4       C        110   5300


In [88]:
df[df['koszt']>5000]
print(df)

  produkt  produkcja  koszt
0       A        100   5000
1       A        120   5500
2       B         90   4500
3       B         95   4700
4       C        110   5300


In [89]:
df[df['produkcja']<100]
print(df)

  produkt  produkcja  koszt
0       A        100   5000
1       A        120   5500
2       B         90   4500
3       B         95   4700
4       C        110   5300


In [ ]:
#analiza danych produkcyjnych

#tworzenie df_z
df_z = pd.DataFrame({
    'nazwa produktu': ['a', 'a', 'c', 'd', 'b'],
    'nakład produkcji': [100, 200, 300, 400, 500],
    'koszt produkcji': [5000, 4000, 3000, 2000, 1000]
})

print(df_z.head())
print(df_z.info())
print(df_z[df_z['nakład produkcji'] > 300])
print(df_z.groupby('nazwa produktu')['koszt produkcji'].mean())

  nazwa produktu  nakład produkcji  koszt produkcji
0              a               100             5000
1              a               200             4000
2              c               300             3000
3              d               400             2000
4              b               500             1000
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nazwa produktu    5 non-null      str  
 1   nakład produkcji  5 non-null      int64
 2   koszt produkcji   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes
None
  nazwa produktu  nakład produkcji  koszt produkcji
3              d               400             2000
4              b               500             1000
nazwa produktu
a    4500.0
b    1000.0
c    3000.0
d    2000.0
Name: koszt produkcji, dtype: float64


In [91]:
srednia_produkcji = df_z.groupby('nazwa produktu')['koszt produkcji'].mean()
print('Produkt z najwyższą średnią produkcją', srednia_produkcji.idxmax())

duzy_naklad = df_z[df_z['nakład produkcji'] > 300]['nazwa produktu'].tolist()
print('Produkty z nakładem powyżej 300: ', duzy_naklad)

print('Liczba kolumn w danych: ', df_z.shape[1])

Produkt z najwyższą średnią produkcją a
Produkty z nakładem powyżej 300:  ['d', 'b']
Liczba kolumn w danych:  3


#### Mini zadanie 2

In [92]:
import pandas as pd
df = pd.DataFrame({
 'produkt': ['A', 'A', 'B', 'C', 'C'],
 'produkcja': [100, 120, 90, 130, 110],
 'koszt': [5000, 6000, 4500, 7000, 6500],
 'czas': [10, 12, 5, 15, 4]
})

print(f"Wyświetlona tabela: {df}")
print(f"Pierwsze rekordy:")
df.head()
print('Dane o tabeli: ')
df.info()
df.shape
print(f"Rekordy z produkcją większą niz 100 {df[df['produkcja']>100]['produkt'].tolist}")
srednia_produkcja = df.groupby('produkt')['produkcja'].mean()
print(f"Średnia produkcja dla każdego produktu {srednia_produkcja}")


Wyświetlona tabela:   produkt  produkcja  koszt  czas
0       A        100   5000    10
1       A        120   6000    12
2       B         90   4500     5
3       C        130   7000    15
4       C        110   6500     4
Pierwsze rekordy:
Dane o tabeli: 
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   produkt    5 non-null      str  
 1   produkcja  5 non-null      int64
 2   koszt      5 non-null      int64
 3   czas       5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes
Rekordy z produkcją większą niz 100 <bound method IndexOpsMixin.tolist of 1    A
3    C
4    C
Name: produkt, dtype: str>
Średnia produkcja dla każdego produktu produkt
A    110.0
B     90.0
C    120.0
Name: produkcja, dtype: float64


#### Utworzenie przykładowego zbioru z błędami

In [93]:
import pandas as pd
import numpy as np

produkt = np.array['A', 'b', None, 'C', 'a']
produkcja = np.array[100, 0, 120, -5, 90]
plan = np.array[120, 100, np.nan, 110, 100]
koszt = np.array['5000', '4500', '5200', None, '4800']

df = pd.DataFrame({
    'produkt': produkt,
    'produkcja': produkt,
    'plan': plan,
    'koszt': koszt
})

print(df)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [94]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'produkt': ['A', 'b', None, 'C', 'a'],
    'produkcja': [100, 0, 120, -5, 90],
    'plan': [120, 100, np.nan, 110, 100],
    'koszt': ['5000', '4500', '5200', None, '4800']
})

print(df)

  produkt  produkcja   plan koszt
0       A        100  120.0  5000
1       b          0  100.0  4500
2     NaN        120    NaN  5200
3       C         -5  110.0   NaN
4       a         90  100.0  4800


#### Sprawdzanie braków danych

In [ ]:
#wykrywanie pustych wartości
df.isnull().sum()

produkt      1
produkcja    0
plan         1
koszt        1
dtype: int64

In [96]:
df_null = df.isnull().sum()
df_null_max = df_null.max()

df_kolumny = df_null[df_null == df_null_max].index.tolist()
print(f"Kolumna z największą liczbą nulli: {df_kolumny}")

Kolumna z największą liczbą nulli: ['produkt', 'plan', 'koszt']


#### Usuwanie brakujących danych

In [ ]:
#metoda dropna()
df_dropna = df.dropna()
print(df_dropna)

  produkt  produkcja   plan koszt
0       A        100  120.0  5000
1       b          0  100.0  4500
4       a         90  100.0  4800


In [98]:
rekordy_przed = df.shape[0]
rekordy_po = df_dropna.shape[0]

if rekordy_przed == rekordy_po:
    print('Liczba rekordów jest taka sama')
else:
    print('Liczba rekordów różna')

Liczba rekordów różna


#### Uzupełnianie braków danych

In [ ]:
#fillna()
df_fill = df.fillna(0)
print(df_fill)

  produkt  produkcja   plan koszt
0       A        100  120.0  5000
1       b          0  100.0  4500
2       0        120    0.0  5200
3       C         -5  110.0     0
4       a         90  100.0  4800


In [ ]:
#porównanie dropna() i fillna(0)
rekordy_fill = df_fill.shape[0]
if rekordy_przed == rekordy_po:
    print('Liczba rekordów po drop się nie zmieniła')
elif rekordy_przed == rekordy_fill:
    print('Liczba rekordów po drop się zmieniła ale po fill nie')
else:
    print('Liczba rekordów różna w obu metodach')

Liczba rekordów po drop się zmieniła ale po fill nie


#### Tworzenie nowej kolumny

In [101]:
df['plan'] = df['plan'].fillna(100)
df['wydajnosc'] = (df['produkcja']/df['plan']*100).round(2)
print(df)

  produkt  produkcja   plan koszt  wydajnosc
0       A        100  120.0  5000      83.33
1       b          0  100.0  4500       0.00
2     NaN        120  100.0  5200     120.00
3       C         -5  110.0   NaN      -4.55
4       a         90  100.0  4800      90.00


#### Zmiana typu danych

In [102]:
print(f"Typ kolumny koszt przed zmianą: {df['koszt'].dtype}")
df['koszt'] = df['koszt'].fillna('0')
df['koszt'] = df['koszt'].astype(float)
print(f"Typ kolumny koszt po zmianie: {df['koszt'].dtype}")

Typ kolumny koszt przed zmianą: str
Typ kolumny koszt po zmianie: float64


#### Usuwanie błędnych rekordów

In [103]:
print(f"Tabela przed usunięciem")
print(df)

print(f"Tabela po usunięciu")
df = df[df['produkcja'] > 0]
print(df)

Tabela przed usunięciem
  produkt  produkcja   plan   koszt  wydajnosc
0       A        100  120.0  5000.0      83.33
1       b          0  100.0  4500.0       0.00
2     NaN        120  100.0  5200.0     120.00
3       C         -5  110.0     0.0      -4.55
4       a         90  100.0  4800.0      90.00
Tabela po usunięciu
  produkt  produkcja   plan   koszt  wydajnosc
0       A        100  120.0  5000.0      83.33
2     NaN        120  100.0  5200.0     120.00
4       a         90  100.0  4800.0      90.00


#### Standaryzacja danych tekstowych

In [ ]:
#uzupełnienie wartości null w kolumnie produkt
df['produkt'] = df['produkt'].fillna('BRAK')

#standaryzacja zapisu
df['produkt'] = df['produkt'].str.upper()

#wyświetlenie df
print(df)

  produkt  produkcja   plan   koszt  wydajnosc
0       A        100  120.0  5000.0      83.33
2    BRAK        120  100.0  5200.0     120.00
4       A         90  100.0  4800.0      90.00


#### Łączenie kilku operacji

In [ ]:
#pełny proces przygotowania danych
df = pd.DataFrame({
    'produkt': ['A', 'b', None, 'c', 'd', 'B'],
    'produkcja': [100, 0, -5, 90, 240, 90],
    'plan': [120, 0, np.nan, 100, 240, 50],
    'koszt': ['120', '0', None, '100', '240', '50'],
    'czas': ['','120','50','12',None,'123'],
    'magazyn': [140, 30, 190, np.nan, -10, 50],
})

#dane wstępne 
print(f"Dane początkowe: {df}")

Dane początkowe:   produkt  produkcja   plan koszt czas  magazyn
0       A        100  120.0   120         140.0
1       b          0    0.0     0  120     30.0
2     NaN         -5    NaN   NaN   50    190.0
3       c         90  100.0   100   12      NaN
4       d        240  240.0   240  NaN    -10.0
5       B         90   50.0    50  123     50.0


In [ ]:
#sprawdzenie ilości braków w danych
print(f"Braki danych: {df.isnull().sum()}")

#output: jeśli w zbiorze danych jest pusty ciąg znaków funkcja isnull go nie wskazuje
#co oznacza, że funkcja fillna() go nie wypełni - trzeba zrobić to w inny sposób
#np. zmienić pusty ciąg znaków na null a później na całości użyć funkcji fillna()

Braki danych: produkt      1
produkcja    0
plan         1
koszt        1
czas         1
magazyn      1
dtype: int64


In [ ]:
#zamiana pustych ciągów znaków na wartości null
df = df.replace(r'^\s*$', np.nan, regex=True)

#sprawdzenie ile null
print(f"Braki danych: {df.isnull().sum()}")
print(df.dtypes)

Braki danych: produkt      1
produkcja    0
plan         1
koszt        1
czas         2
magazyn      1
dtype: int64
produkt          str
produkcja      int64
plan         float64
koszt            str
czas             str
magazyn      float64
dtype: object


In [120]:
#uzupełnienie braków w danych

#kolumny liczbowe
df['plan'] = df['plan'].fillna(0)
df['magazyn'] = df['magazyn'].fillna(0)

#kolumny tekstowe
df['produkt'] = df['produkt'].fillna('BRAK')
df['koszt'] = df['koszt'].fillna('BRAK')
df['czas'] = df['czas'].fillna('BRAK')

#wyświetlenie uzupełnionego df
print(df)

  produkt  produkcja   plan koszt  czas  magazyn
0       A        100  120.0   120  BRAK    140.0
1       b          0    0.0     0   120     30.0
2    BRAK         -5    0.0  BRAK    50    190.0
3       c         90  100.0   100    12      0.0
4       d        240  240.0   240  BRAK    -10.0
5       B         90   50.0    50   123     50.0


In [126]:
#wykluczenie danych dla produkcji <=0
df = df[df['produkcja'] > 0]

#przypisanie poprawnych typów danych
df['koszt'] = df['koszt'].astype(float)

#ujednolicenie zapisu
df['produkt'] = df['produkt'].str.upper()

#dodanie brakującej kolumny wydajność
df['wydajnosc'] = df['produkcja'] / df['plan'].replace(0,
np.nan) * 100

#oczyszczone dane
print(f"Dane po przygotowaniu: {df}")

Dane po przygotowaniu:   produkt  produkcja   plan  koszt  czas  magazyn   wydajnosc
0       A        100  120.0  120.0  BRAK    140.0   83.333333
3       C         90  100.0  100.0    12      0.0   90.000000
4       D        240  240.0  240.0  BRAK    -10.0  100.000000
5       B         90   50.0   50.0   123     50.0  180.000000


#### Dataset gotowy do analizy

In [127]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, 0 to 5
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   produkt    4 non-null      str    
 1   produkcja  4 non-null      int64  
 2   plan       4 non-null      float64
 3   koszt      4 non-null      float64
 4   czas       4 non-null      str    
 5   magazyn    4 non-null      float64
 6   wydajnosc  4 non-null      float64
dtypes: float64(4), int64(1), str(2)
memory usage: 256.0 bytes


Dane mają poprawne typy danych nie występują pustę wartości w kolumnach.

#### Mini zadanie 3 podsumowanie

In [ ]:
#definicja dataframe
df=pd.DataFrame({
    "Kolumna 1": [1,2,3]
})

#zmiana pustych ciągów znków na null

#sprawdzenie braków

#uzupełnienie brakujących wartości 0/BRAK

#usunięcie rekordów w których produkcja <=0

#zmiana typów kolumny koszt na float

#utworzenie nowej kolumny wydajność

#ujednolicenie nazw produktów